# Generated by Django 5.2 on 2025-09-20 08:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='download_uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Download UUID'),
        ),
    ]
