# Generated by Django 5.2 on 2025-09-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_download_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='download_uuid',
            field=models.UUIDField(unique=True, verbose_name='Download UUID'),
        ),
    ]
