# Generated by Django 5.2 on 2025-09-20 10:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Job ID')),
                ('task_id', models.UUIDField(blank=True, null=True, verbose_name='Background Task ID')),
                ('url', models.URLField(max_length=500, verbose_name='YouTube URL')),
                ('download_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10, verbose_name='Download Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('downloading', 'Downloading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Filename')),
                ('filepath', models.TextField(blank=True, null=True, verbose_name='File Path')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('error_details', models.JSONField(blank=True, null=True, verbose_name='Error Details')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('download_source', models.CharField(default='api', max_length=20, verbose_name='Download Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Download Job',
                'verbose_name_plural': 'Download Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Video Title')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('uploader', models.CharField(blank=True, max_length=200, null=True, verbose_name='Uploader')),
                ('upload_date', models.DateField(blank=True, null=True, verbose_name='Upload Date')),
                ('view_count', models.BigIntegerField(blank=True, null=True, verbose_name='View Count')),
                ('like_count', models.BigIntegerField(blank=True, null=True, verbose_name='Like Count')),
                ('format_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Format ID')),
                ('ext', models.CharField(blank=True, max_length=10, null=True, verbose_name='File Extension')),
                ('vcodec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Video Codec')),
                ('acodec', models.CharField(blank=True, max_length=50, null=True, verbose_name='Audio Codec')),
                ('filesize', models.BigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('fps', models.FloatField(blank=True, null=True, verbose_name='FPS')),
                ('raw_metadata', models.JSONField(blank=True, null=True, verbose_name='Raw Metadata')),
                ('download_speed', models.FloatField(blank=True, null=True, verbose_name='Download Speed (MB/s)')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('deletion_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Deletion Reason')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='audio_dl.downloadjob', verbose_name='Download Job')),
            ],
            options={
                'verbose_name': 'Job Metadata',
                'verbose_name_plural': 'Job Metadata',
                'ordering': ['-job__created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['user', 'created_at'], name='audio_dl_do_user_id_76785d_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['status', 'created_at'], name='audio_dl_do_status_65a840_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['job_id'], name='audio_dl_do_job_id_de6472_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadjob',
            index=models.Index(fields=['task_id'], name='audio_dl_do_task_id_5f23af_idx'),
        ),
    ]
